apiVersion: apps/v1

kind: Deployment

metadata:
  name: first-deployment
  labels:
    app: nginx-test

spec:
### REPLICASET SPEC ####
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
### POD SPEC ###
  template:
    metadata:
      name: mouli
      labels:
        app: nginx-test

    spec:
      containers:
        - name: chaitu
          image: nginx
