apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    name: demo
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2-service
spec:
  selector:
    name: demo
  ports:
  - name: nginx-2-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
