apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: elasticsearch
  labels:
    app: elasticsearch

spec:
### REPLICASET SPEC ####
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: "elasticsearch"
### POD SPEC ###
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch

    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
