apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-cm

spec:
  containers:
    - name: demo-container
      image: nginx
      volumeMounts:
      - name: configmap-mount
        mountPath: "/trainings"
        readOnly: true
      - name: nginx-configmap
        mountPath: "/usr/share/nginx/html/"

  volumes:
    - name: configmap-mount
      configMap:
        name: demo-cm
    - name: nginx-configmap
      configMap:
        name: nginx-cm
