apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>

    <h1>Hi team, it is a DEMO page for configMap check</h1>
    <p>By Mouli.</p>

    </body>
    </html>