apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab-nginx
  name: yaml-nginx
  namespace: lab
spec:
  containers:
  - image: nginx
    name: yaml-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
