apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: mouli
  namespace: lab

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
### POD SPEC ###
  template:
    metadata:
      name: mouli
      labels:
        app: nginx-test

    spec:
      containers:
        - name: chaitu
          image: nginx
