apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-with-env
  namespace: demo-2
  labels:
    name: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80  
    env:
    - name: NAME
      value: Mouli
    - name: NAME2
      value: DEMO
