apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-4
  namespace: demo
  labels:
    name: ganesh
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80  
  nodeName: minikube-multi-m03
