apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-with-cm
  namespace: demo-2
  labels:
    name: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80  
    env:
    - name: NAME_ENV
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: NAME
    - name: PHONE
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: PH
