apiVersion: apps/v1

kind: Deployment

metadata:
  name: hello-deployment
  labels:
    app: demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: helloapp
        image: mouliveera/hellodockerimage:latest
        ports:
        - containerPort: 80
