apiVersion: apps/v1

kind: Deployment

metadata:
  name: my-deployment
  labels:
    app: demo

spec:
  replicas: 2
  selector:
    matchLabels:
      deploy: my-deployment
  template:
    metadata:
      labels:
        deploy: my-deployment  
    spec:
      containers:
      - name: nginx
        #image: nginx:1.14.2
        image: nginx
        ports:
        - containerPort: 80
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
