apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: demo-cluster-ip-svc
  ports:
    - targetPort: 80
      port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ip-deploy
  labels:
    app: demo-cluster-ip-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: nginx:1.22
        name: nginx-test
