apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - name: http
    port: 80
    targetPort: 80
#    nodePort: 30007 #(default: 30000-32767)
