apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-service-deploy
  labels:
    app: demo-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: nginx:1.22
        name: nginx-test
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  selector:
    app: demo-lb
  ports:
  - name: http
    port: 80
    targetPort: 80
