apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-replicaset-res
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: nginx:1.23
        name: nginx-test
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"
