apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: lab-cm
      mountPath: "/tmp/trainings"
      readOnly: true
  volumes:
  - name: lab-cm
    configMap:
      name: lab-cm
