apiVersion: v1

kind: ConfigMap

metadata:
  name: firstdeploy-cm
  annotations:
    reloader.stakater.com/match: "true"

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>

    <h1>This is a TEST NGINX page</h1>

    <p>By MouliDeepika</p>

    </body>
    </html>


