apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  claimRef:
    namespace: demo
    name: demo-pvc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/