version: '3'

services:
  nginx:
    image: ubuntu:20.04
    #container_name: my-nginx-container
    command: /bin/bash -c "apt-get update && apt-get install -y nginx && nginx -g 'daemon off;'"
#    ports:
#      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - nginx_network
    deploy:
      mode: replicated
      replicas: 2

#networks:
#  nginx_network:
#    driver: bridge

