FROM ubuntu:18.04
RUN apt-get update

#RUN apt-get install -y python

#COPY . /tmp/
#RUN chmod +x /tmp/app.sh

#ENTRYPOINT /tmp/app.sh

CMD "echo Hello World"
#CMD ['echo', 'Hello world']
#CMD ['/tmp/app.sh']
