apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /sukesh
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
