apiVersion: v1
kind: Pod
metadata:
  name: nginx-init-container
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  initContainers:
  - name: nginx-config
    image: busybox
    command: ['sh', '-c', 'echo "Welcome team for Kubernetes learning!" > /usr/share/nginx/html/index.html']
  volumes:
  - name: nginx-config-volume
    emptyDir: {}

