apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
data:
  index.html: |
    Welcome team for Kubernetes learning!

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-init-container
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  initContainers:
  - name: nginx-config
    image: busybox
    command: ['sh', '-c', 'echo "$HTML_CONTENT" > /usr/share/nginx/html/index.html']
    env:
    - name: HTML_CONTENT
      valueFrom:
        configMapKeyRef:
          name: nginx-index-html
          key: index.html
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-config-volume
    emptyDir: {}

