apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-replicaset
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo-pod
      namespace: qa
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
