apiVersion: v1
kind: Service
metadata:
  name: external-service
  namespace: demo
spec:
  type: ExternalName
  externalName: myservice.example.com
  selector:
    app: demo-exter-svc
    #matchLabels:
    #  app: demo-exter-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-deploy
  labels:
    app: demo-exter-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: nginx:1.22
        name: nginx-test
