apiVersion: apps/v1

kind: Deployment

metadata:
  name: demo-deploy
  labels:
    env: green
    app: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      env: green
  template:
    metadata:
      name: naresh-demo
      labels:
        env: green
    spec:
      containers:
      - name: samba-demo
        image: nginx:1.22.0
