apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      name: static-web-1
      namespace: dev
      labels:
        app: dev
    spec:
      containers:
        - name: web
      #image: nginx
          image: nginx
          ports:
            - name: web
              containerPort: 80
              protocol: TCP

