apiVersion: v1
kind: Pod
metadata:
  name: static-web-2
  namespace: dev
  labels:
    app: dev
spec:
  containers:
    - name: web
      #image: nginx
      image: bitnami/nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
