apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
  labels:
    env: dev
spec:
  replicas: 2
  template:
    metadata:
      name: static-web-1
      namespace: dev
      labels:
        app: nginx
        env: dev
    #app: nginx
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
        - name: mouli
          image: redis
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
