apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-secrets

spec:
  containers:
    - name: demo-container
      image: nginx
      volumeMounts:
      - name: secrets-mount
        mountPath: "/secrets"
        readOnly: true


  volumes:
    - name: secrets-mount
      secret:
        secretName: demo-secrets


