version: '3'

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx1/conf.d:/etc/nginx/conf.d
      - ./nginx1/html:/usr/share/nginx/html

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx2/conf.d:/etc/nginx/conf.d
      - ./nginx2/html:/usr/share/nginx/html

