configuration:
  backupStorageLocation:
  - bucket: velero-awseksbackup
    name: velero-awseksbackup
    provider: aws
    prefix: velero
    default: true
    config:
      region: us-east-1
  volumeSnapshotLocation:
  - config:
      region: us-east-1
    provider: aws
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.8.1
  volumeMounts:
  - mountPath: /target
    name: plugins
credentials:
  useSecret: false
serviceAccount:
  server:
    create: true
    name: velero-demo-sa
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::636493328516:role/velero-role"
