configuration:
  backupStorageLocation:
  - bucket: velero-awseksbackup
    name: velero-awseksbackup
    provider: aws
    prefix: velero
    default: true
    config:
      region: minio
      s3ForcePathStyle: true
      s3Url: http://minio.velero.svc:9000
  volumeSnapshotLocation:
  - config:
      region: minio
      s3ForcePathStyle: true
      s3Url: http://minio.velero.svc:9000
    provider: aws
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.8.1
  volumeMounts:
  - mountPath: /target
    name: plugins
credentials:
  useSecret: true
  secretContents:
    cloud: credentials-velero
#serviceAccount:
#  server:
#    create: true
#    name: velero-demo-sa
#    annotations:
#      eks.amazonaws.com/role-arn: "arn:aws:iam::636493328516:role/velero-role"

#---
#❯ velero install \
#    --provider aws \
#    --plugins velero/velero-plugin-for-aws:v1.2.1 \
#    --bucket velero \
#    --secret-file ./credentials-velero \
#    --use-volume-snapshots=false \
#    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.velero.svc:9000

