version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
    ports:
      - "4000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
