apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
      containers:
      - name: demo-container
        image: busybox
        command: ["echo", "Hello from the job"]
      restartPolicy: Never
  backoffLimit: 4

