# ConfigMap definition
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  username: TEST

---
# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-app
  template:
    metadata:
      labels:
        app: cm-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest  # Using the Nginx image
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: username

