apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-sc-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard" # Empty string must be explicitly set otherwise default StorageClass will be set
  resources:
    requests:
      storage: 2Gi