apiVersion: v1
kind: Pod
metadata:
  name: demo-sc-pod
spec:
   containers:
   - name: demo-sc-container
     image: nginx
     volumeMounts:
      - mountPath: "/app/data"
        name: my-volume
   volumes:
   - name: my-volume
     persistentVolumeClaim:
       claimName: demo-sc-pvc