---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gbook-ingress
spec:
  rules:
  - host: "trainings.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: 80