apiVersion: v1
kind: Pod
metadata:
  name: init-pod-2
spec:
  volumes:
  - name: mydir
    emptyDir: {}
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: ['sh', '-c', 'mkdir /trainings; touch /trainings/test.txt']
    volumeMounts:
    - name: mydir
      mountPath: /trainings
  containers:
  - name: my-container
    image: alpine
    command:
    - sh
    - "-c"
    - "a=0; while [ $a -lt 10 ]; do echo 'Creating file $a' ;echo '-------------'; touch /train/file-$a; max=$(expr $a + 1); done; sleep 99999"
    volumeMounts:
    - name: mydir
      mountPath: /train
