apiVersion: apps/v1

kind: Deployment

metadata:
  name: hello-deployment
  labels:
    app: demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        #image: nginx:1.14.2
        image: mouliveera/hellodockerimage:latest
        ports:
        - containerPort: 80
#      - name: redis
#        image: redis
#        ports:
#        - containerPort: 6379
