apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: static-web-1
      namespace: dev
      labels:
        app: nginx
        #app: nginx
    spec:
      containers:
        - name: web
          #image:
          image: bitnami/nginx
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
        - name: mouli
          image: redis
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
