#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend
#  labels:
#    app: guestbook
#    tier: frontend
#spec:
#  type: NodePort
#  selector:
#    app: guestbook
#    tier: frontend
#    # the port that this service should serve on
#  ports:
#    - port: 80
#      nodePort: 31000
#      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: guestbook
    tier: frontend
---
