#Redis follower
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
        - name: redis-slave
          image: us-docker.pkg.dev/google-samples/containers/gke/gb-redis-follower:v2
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
