apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/1 * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-container
            image: busybox
            command: ["echo", "Hello from the cronjob"]
          restartPolicy: Never

