apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-with-cm-volume
  namespace: demo-2
  labels:
    name: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80  
    volumeMounts:
    - name: app-props
      mountPath: /demo-apps/  
  volumes:
  - name: app-props
    configMap:
      name: demo-cm-app-props
