---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: dev
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      labels:
        app: rs
    spec:
      affinity:
        # ⬇⬇⬇ This ensures pods will land on separate hosts
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: [{ key: app, operator: In, values: [hello] }]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hello
        image: pbitty/hello-from:latest
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
        - name: hello-configmap
          mountPath: "/mouli/sudheer"
          readOnly: true
      volumes:
        - name: hello-configmap
          configMap:
            name: hello-configmap

