---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: dev
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - protocol: TCP
      nodePort: 32000
      port: 81
      targetPort: 81
