apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-demo
  name: nginx-demo
  namespace: dev
spec:
  containers:
  - image: nginx
    name: nginx-demo
    resources: {}
  - image: redis
    name: redis-demo
  - name: mongo-demo
    image: mongo
