apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo-pod-2
  name: demo-pod-2
spec:
  containers:
  - image: nginx
    name: demo-pod-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
