apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-with-node-name
  namespace: demo
  labels:
    name: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80  
  nodeName: minikube-multi
